# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BRCBoxInputView_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!	
  pod 'BRCBoxInputView'
  pod 'BRCPopUp'
  pod 'BRCFastTest','~> 0.2.3'
  # Pods for BRCBoxInputView_SwiftUI

end
